### ISSUE TITLE
how to catch en event

### ISSUE THREAD

**Issue by noninyo** [handsontable/handsontable-pro#10]
Hi,
I would like to use afterChange event

template:
`<HotTable root="hotgrid" :settings="hotSettings" @afterChange="saveChanges"></HotTable>`
script:
```
export default {
	data: function() {
		return {
			hotSettings: {
				rowHeaders: true,
				columnSorting: true,
				dropdownMenu: true,
				data: [['11','22','33'],['121','232','432']],
				colHeaders: ['A','B','C'],
			}
		}
	},
       methods: {
               saveChanges: function(change, source) {
			console.log(change)
			console.log(source)
       }
}
```
            
Thanks!

**Comment by AMBudnik** [comment]
Hi @noninyo 

please add the task to the[ correct repository](https://github.com/handsontable/hot-table). This repository is only for PRO features of Handsontable.

**Comment by noninyo** [comment]
Done, Thanks
