### ISSUE TITLE
[2.0.0+] Missing colheaders in collapsible/edit option

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable-pro#105]
### Description
Missing colheaders in collapsible/edit option

### Steps to reproduce
Collapse all the columns
Select all cells and remove their content
Expand any column (in my example it was E)

### Demo
https://docs.handsontable.com/pro/4.0.0/demo-collapsing-columns.html

### Related issue
https://github.com/handsontable/handsontable/issues/5188

**Comment by wojciechczerniak** [comment]
5.0.2-RC: http://jsfiddle.net/sv4jgc21/ 👍
