### ISSUE TITLE
can not filter when column is using getter

### ISSUE THREAD

**Issue by chenbojian** [handsontable/handsontable-pro#14]
We are currently encountering this issue about filter.
The code is here https://jsfiddle.net/chenbojian/we7L69yb/1

We are using getter function as data in column B and C. If you filter in column A it will be correct. But if you filter in column B or column C you will find nothing shows up.

**Comment by AMBudnik** [comment]
Hi @chenbojian 

Sorry for keeping you waiting.

You are missing the 'filter_action_bar' https://jsfiddle.net/handsoncode/3gdofyas/ so the filtering never happens

**Comment by chenbojian** [comment]
Hi @AMBudnik 
Thank you for your reply. I missed that menu action. I have updated the code. https://jsfiddle.net/chenbojian/we7L69yb/ . You can reproduce that error. I already know the reason and sent a pull request there.

**Comment by AMBudnik** [comment]
Thank you very much. I will mark it as an issue.

**Comment by AMBudnik** [comment]
This issue is no longer replicable in v 7.0.0 (and 6.2.2) https://jsfiddle.net/3a2bjesy/
