### ISSUE TITLE
Add hooks: beforeRowsHide / aferRowsHide

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable-pro#163]
@AMBudnik commented on [Wed Apr 12 2017](https://github.com/handsontable/handsontable/issues/4187)

### Description

We can add this hooks beforeRowsHide / aferRowsHide. Especially because this actions don't trigger beforeChange/afterChange.

### Your environment
* Handsontable version: 1.10.2
`#GL 141`

---

@AMBudnik commented on [Thu Jul 06 2017](https://github.com/handsontable/handsontable/issues/4187#issuecomment-313313223)

The idea has been added to our [wiki section for the Feature Requests](https://github.com/handsontable/handsontable/wiki/Feature-requests). 

---

@AMBudnik commented on [Wed Oct 10 2018](https://github.com/handsontable/handsontable/issues/4187#issuecomment-369238000)

We should also add the same callback for columns.

`inform Gr # 19457`

---

@wojciechczerniak commented on [Mon Oct 15 2018](https://github.com/handsontable/handsontable/issues/4187#issuecomment-429839092)

Just one note, different hook names to be more in line with our current naming convention: beforeHideRows, afterHideRows, beforeHideColumns, afterHideColumns

----------
## Edit:
 Related CE task: handsontable/handsontable#5522

**Comment by wojciechczerniak** [comment]
Moved and done in https://github.com/handsontable/handsontable/pull/5651
