### ISSUE TITLE
How to use getInstance

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable-pro#164]
Hello,

I try to use the getInstance function like this 

function getHandsontable(){
			var $oContainer = document.getElementById('handsontable-container');
			return $oContainer.Handsontable('getInstance');
}

But the console displays this error "Uncaught TypeError: $oConteneurGrilleResultat.Handsontable is not a function"

Regards

**Comment by AMBudnik** [comment]
Hi @LoveOfLava 

Can I ask you to create a full demo of the approach?

**Comment by wojciechczerniak** [comment]
We can't help without the demo. I'm closing this issue.
