### ISSUE TITLE
Formulas MIN and MAX are breaking after change reference cell content

### ISSUE THREAD

**Issue by rbarato** [handsontable/handsontable-pro#166]
### Description
When I have a MIN/MAX formula using cell references, after the reference changes, the formula loses the reference.

Further investigating I noticed that on change, the value is passed to the formula parser as string and is removed from the range array. I've setup the HOT with this column being type numeric but the issue persists.

### Steps to reproduce
1. Have some cell with the value: =MIN(A1;A2;A3)
2. On cells A1:A3 set: 1; 2; 3
3. Change any of the values to 0, the formula should calculate 0 as min but it's not.

Extra: if you remove the formula and add it again, the formula parses correctly.

### Demo
https://jsfiddle.net/thn3o92c/2/

![oct-22-2018 11-13-32](https://user-images.githubusercontent.com/1949592/47297478-8cbc9480-d5eb-11e8-940e-4491f7369035.gif)

![oct-22-2018 11-08-38](https://user-images.githubusercontent.com/1949592/47297417-68f94e80-d5eb-11e8-80a2-8353b3ac0384.gif)

### Your environment
* Handsontable version: 5.0.2
* Browser Name and version: Chrome 69
* Operating System: MacOs High Sierra

**Comment by AMBudnik** [comment]
Thank you for sharing and investigating the issue @rbarato 

I believe that this is the same case as this one https://github.com/handsontable/handsontable/issues/5285

If I am missing something please please an additional comment at https://github.com/handsontable/handsontable/issues/5285
