### ISSUE TITLE
Why is yarn a dependency?

### ISSUE THREAD

**Issue by tzimmermann** [handsontable/handsontable-pro#167]
### Description
Since `v5.0.0`, it seems that `yarn` has been added as a direct dependency in the `package.json`.
I cannot really imagine that this was done on purpose, since I cannot find any mention of `yarn` anywhere in the source.

Also, it would be *really* unusual to specify a package manager like `yarn` as a direct dependency.

Seems like it has been added with https://github.com/handsontable/handsontable-pro/commit/6f0092840906e469133112291b65ab6803bb3038.

**Comment by budnix** [comment]
Yep, you are right! This shouldn't happen. In today's release, this will be removed from our dependencies.

Please keep this issue open after we released fixed version.
