### ISSUE TITLE
Vertical virtual scrolling broken with nested headers and tall rows

### ISSUE THREAD

**Issue by psalaets** [handsontable/handsontable-pro#18]
This is a pretty specific use case, but it appears that having tall rows with nested headers does something to height calculations used by virtual scrolling.

## Scenario

- Fixed width columns and long cell values that wrap so much that the row height > viewport height
- Nested headers
- Virtual scrolling

## fiddle

https://jsfiddle.net/09rg6f1s/13/

Try to scroll to row 2. Row 1 scrolls away but other rows never show up.

## Workaround

Calling `hotInstance.render()` after vertical scroll seems to fix the issue.

**Comment by AMBudnik** [comment]
Thank you very much for sharing @psalaets 

The issue has been reported some time ago for the CE version at https://github.com/handsontable/handsontable/issues/4173.
It looks like the core is responsible for this bug.

Please track changes to https://github.com/handsontable/handsontable/issues/4173 for updates
