### ISSUE TITLE
When we enable filters/trimRows we aren't able to add new rows while pasting data

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable-pro#181]
### Description
https://github.com/handsontable/handsontable/issues/5565

### Steps to reproduce

1. Copy this data
```
2/5/2018
2/11/2018
2/11/2018
2/11/2018
2/5/2018
22/11/2018
2/5/2018
2/5/2018
22/5/2018
```
2. Paste it to cell 0,0 or 0,1.

### Demo

https://jsfiddle.net/1b4xyav0/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Same as https://github.com/handsontable/handsontable/issues/5648
