### ISSUE TITLE
how to render the edited data which has not been saved in database even after page refresh 

### ISSUE THREAD

**Issue by primeO** [handsontable/handsontable-pro#184]
### Description
1. handsongrid will be opened for first time .
2. user will edit some of the data 
3. he hadnt saved the grid 
4. he had closed the panel and again revisits the panel 
5. data which has been edited should be rendered 

Is this feature available in handsontable ?

### Your environment
* Handsontable version: Handson PRO 
* Browser Name and version: Chrome and Safari 
* Operating System: Windows

**Comment by primeO** [comment]
@AMBudnik , i had used afterchange which are reflecting the changes which has made by the user the below is the snippet . 

```
afterChange: function (change, source) {
								  if (source === "loadData") {
									  if (localStorage['data']) {
						                    var data1 = JSON.parse(localStorage['data'])
						                    alert(data1);
						                  // this.loadData(data1);
						                   // this.render();
						                    return
						                }
									  }
								  else {
						                // save all data to local storge if the edit happends
						                localStorage['data'] = JSON.stringify(this.getData());
						                return
						            }

						        }
```
but how to append  this as a data which iam facing issue why means already data has been assigned to the json url .

**Comment by AMBudnik** [comment]
I am sorry but I do not understand the request.

MAybe you'll be able to send a demo with your recent progress?

**Comment by primeO** [comment]
ok @AMBudnik

**Comment by primeO** [comment]
@AMBudnik  , Thanks for the inputs . I had done this by making few changes in the flow of the application  .

**Comment by AMBudnik** [comment]
Great. Thank you for confirmation.

I guess that we can close this topic.
