### ISSUE TITLE
Unable to sort correctly with rendered HTML

### ISSUE THREAD

**Issue by danives3d** [handsontable/handsontable-pro#191]
### Description
When using the HTML renderer, the data doesn't sort as you would expect.

### Steps to reproduce

1. Create a new data table with a HTML column, with links e.g. <a href="a">c</a>, <a href="b">a</a>, <a href="c">b</a>
2. Sent columnSorting to "true"
3. Attempt to sort, and note the text in the HTML doesn't change

### Demo
https://jsfiddle.net/mdgoq8wp/

### Your environment
* Handsontable version: 6.2.1
* Browser Name and version: Chrome Version 70.0.3538.110
* Operating System: OSX

### Possible Solution

In the `sortByPresetSortStates` function, and the subfunction `getDataForSortedColumns`, stripping the html fixes this issue. See example below:

```
value: function sortByPresetSortStates() {
      ...
      var stripHTML = function(a) {
        var tmp = document.createElement("DIV");
        tmp.innerHTML = a;
        return tmp.textContent || tmp.innerText || "";
      }
      ...
      var getDataForSortedColumns = function getDataForSortedColumns(visualRowIndex) {
        return (0, _array.arrayMap)(sortedColumnsList, function (physicalColumn) {
          return stripHTML(_this10.hot.getDataAtCell(visualRowIndex, _this10.hot.toVisualColumn(physicalColumn)));
        });
      };
```

Either that, or a change to `toVisualColumn` but I don't know what the full ramifications would be for that.

**Comment by danives3d** [comment]
Our issue with that approach is that we have multiple columns, each with anchor tags that go to different places dependant on the value - its not solely based on the 'data'.

e.g. <a href="/1">a</a>, <a href="/95">b</a>, <a href="/question">c</a>

So if we were to take the approach you suggest, we'd also need to create an entirely separate relational dataset to pass through to the renderer, to decide what HTML to use based on the row index - whereas simply stripping the HTML in that one place in your codebase achieves the same thing with less overhead.

If it were an option that could be enabled/disabled, then it would also mean that people who did want their data to be sorted based on the invisible rendered HTML would still be able to have that - however, I can't see many instances where someone would want rendered HTML sorted in that fashion.

**Comment by AMBudnik** [comment]
Hey @danives3d 

I've just replied to your next issue with a very similar demo as before. The idea with the filter_by_value is a good idea, however, now the filtering and sorting can only be done the way I've shown you. I can imagine that it can take more coding than expected.

**Comment by AMBudnik** [comment]
Good news @danives3d 

I just got a hint that there's no need for doing any changes in our code. You're introducing custom data type so you need to provide `compareFunction` for that data type.

The option you are looking for:
https://handsontable.com/docs/6.2.2/demo-sorting.html#custom-compare-functions

And a blog post with an example (look for star rating):
https://handsontable.com/blog/articles/2018/11/feature-spotlight-multi-column-sorting
