### ISSUE TITLE
Is there any option for download grid as PDF and TXT 

### ISSUE THREAD

**Issue by primeO** [handsontable/handsontable-pro#192]
### Description
How to export the grid to PDF and TXT . CSV i had tested and integrated it is working . Is PDF and TXT export is part of release when it will be released . 

### Your environment
* Handsontable version: PRO Version 6
* Browser Name and version: Chrome 
* Operating System:Windows

**Comment by AMBudnik** [comment]
Hey @primeO 

Currently, we only allow exporting the table to a .csv file.
