### ISSUE TITLE
How to get only the edited data to the console 

### ISSUE THREAD

**Issue by primeO** [handsontable/handsontable-pro#193]
### Description
With Data we will be getting the data from Bean / Rest API . Once the user made few changes in the grid only those rows with data should be printed in the console . 

Any demo which is already available 

### Your environment
* Handsontable version: Pro Version
* Browser Name and version: Chrome 
* Operating System: Windows

**Comment by AMBudnik** [comment]
Hey @primeO 

I think that you can use the `afterChange` hook to gather an array of indexes for the changed rows.

> Once the user made few changes in the grid only those rows with data should be printed in the console

Like `afterChange` 1st param is `changes` array where we get `[row_index, column_index, old_value, new_value]`.

[var arrayOfIndexes = []
afterChange(source) > arrayOfIndexes.push(source[0][0])](https://jsfiddle.net/7f59w4pa/)

**Comment by primeO** [comment]
Thanks @AMBudnik  ,if i need the data of the rows which edited which structure i need to follow .

**Comment by AMBudnik** [comment]
You'd need to pass the same `arrayOfIndexes` logic to the [`afterCreateRow` ](https://handsontable.com/docs/6.2.1/Hooks.html#event:afterCreateRow)and [`afterRemoveRow` ](https://handsontable.com/docs/6.2.1/Hooks.html#event:afterRemoveRow)logic.

**Comment by primeO** [comment]
Hi @AMBudnik  , let me give a try - if any fiddle it would be helpfull !!
