### ISSUE TITLE
Persist HandsOnTable state

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable-pro#197]
### Description
Is there any way to store the handsontable state in sever side, like its column,order,width,show/hided columns etc...

I want to store these table information against each user logged in, and to show it for their every sessions. So i need to persist these values. do we have any in build properties available for this.

### Steps to reproduce

1. 
2.
3.

### Your environment
* Handsontable version: HandsOnTable Pro 6.2.2

**Comment by crazyjavatricks** [comment]
Thanks @AMBudnik , will check with this.

One more thing,
Can we have any option to persist column filter, show/hide, freezed columns.?
I could only find the sorting,column order and width from persistentState.

**Comment by AMBudnik** [comment]
To get the filters and restore them you'd need to make a call to the afterFilter hook and load the result via filter() method. Here is the information received from the hook http://jsfiddle.net/1ddf47ck/
Hiding should be possible to revert after publishing those changes https://github.com/handsontable/handsontable/issues/5522

**Comment by AMBudnik** [comment]
Hey @crazyjavatricks 

happy to announce that we've added the missing hooks https://github.com/handsontable/handsontable/issues/5522
