### ISSUE TITLE
Filter by value:- Issue with checkbox behavior

### ISSUE THREAD

**Issue by crazyjavatricks** [handsontable/handsontable-pro#199]
### Description

While Filtering with HandsOnTable filter by value option, filtering is happening based on the text entered in text field, but by clicking on OK button column is not filtered based on the text entered

### Steps to reproduce

1. Create a table with filter option.
2. Click on the column filter, enter text in 'filter by value'.
3. Filtering will happen based on the text entered(_check boxes will be selected by default_)
4. Click OK button(_Without changing any check boxes_).
5. Column will not be filtered based on the 'filter by value'.

### Demo

https://jsfiddle.net/A6454/xqrmn0ty/11/

Video Reference : [HandsonTableFilterIssue.zip](https://github.com/handsontable/handsontable-pro/files/2827116/HandsonTableFilterIssue.zip)

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71.0.3578.98
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hey @crazyjavatricks 

the input is there to help you pick the options for the checkbox list. It does not add any condition.

**Comment by crazyjavatricks** [comment]
Ok , but by using that 'filter by value' option we are expecting an excel like behavior. that's why its got confused. 
so the behavior like :- by filtering from text box we need to clear all sections and then have to select the one we needed, and click OK button. right.?

**Comment by AMBudnik** [comment]
> so the behavior like :- by filtering from text box we need to clear all sections and then have to select the one we needed, and click OK button. right.?

yes, you can use the `clear` button before typing in the input and after you type what you want, select the remaining checkboxes.

Here https://github.com/handsontable/handsontable/issues/5030 we have a similar request. Please track changes to this issue for updates.
