### ISSUE TITLE
Nested Headers, custom headers and inline filtering

### ISSUE THREAD

**Issue by toresenneseth** [handsontable/handsontable-pro#21]
Hi,

I'm trying to add inline filtering (based on your example here: https://docs.handsontable.com/pro/1.14.3/demo-filtering.html), and it works fine when I'm _not_ using nested headers. If I use nested headers, the headers are recreated on each render, so it requires hacking to retain the filtering values entered by the user between each call to filterPlugin.filter()

I've included a jsfiddle that reproduces the behavior:
http://jsfiddle.net/toresenneseth/x3er5kvh/

Is there a way to prevent / work around this behavior? Is it a bug or intended behavior?

**Comment by AMBudnik** [comment]
Hi @toresenneseth 

the `afterGetColHeader` is called each time the table is being rerendered. You need to keep the value to be able to pass them before table rerenders. You can use the `beforeRender `hook.

**Comment by toresenneseth** [comment]
Yes, storing the HTML elements along with additional state and re-adding them on render works fine, thanks!
