### ISSUE TITLE
Typing file for pro version

### ISSUE THREAD

**Issue by clairepham91** [handsontable/handsontable-pro#22]
Why is the `handsontable.d.ts` missing in `handsontable-pro`? Do you have plan to include it or do we suppose to use the one from CE version? Thanks

**Comment by AMBudnik** [comment]
Hi @clairepham91 

I saw that you also added the comment at https://github.com/handsontable/handsontable/pull/4519
The https://github.com/handsontable/handsontable/pull files are already merged and the version will be pushed today.

There will be another file, especially for PRO. Thank you for posting this here. Your post will remind us to add it.

**Comment by clairepham91** [comment]
@AMBudnik I am unable to upgrade and include the licenseKey right now due to Typescript error. Can you give an estimated time when `handsontable.d.ts` file is included? Thanks

**Comment by snaptopixel** [comment]
@AMBudnik @clairepham91 this is still missing, any updates?

**Comment by AMBudnik** [comment]
Hi @snaptopixel 

Currently, we have a single .ts file for CE and PRO. It just got updated with the https://github.com/handsontable/handsontable/pull/4519 pull request

**Comment by swistach** [comment]
This issue will be not finished in nearest future.
