### ISSUE TITLE
How to use formula with "Object data source with column mapping"?

### ISSUE THREAD

**Issue by jeffrey008** [handsontable/handsontable-pro#223]
I tried to assign this to `columns` option , but is not working. 
```
[
                {data: '=O$1+R$1'},
                {data: '=SUM(A2:A5)'},
                {data: '=SUM(A2:A5)'},
                {data: '=SUM(A2:A5)'},
                {data: 'module.comments', readOnly: false},
]
```

**Comment by AMBudnik** [comment]
Hey  @jeffrey008 

data must be a key for objects or number (index) for arrays. Here are the examples https://jsfiddle.net/5trqp93f/

**Comment by jeffrey008** [comment]
I am using the formula plugin with object data. Is that possible?

**Comment by AMBudnik** [comment]
I've sent you a message on the second comment you've posted. Please send me a demo (ideally in JSFiddle) and I'll do my best to share some ideas.

**Comment by jeffrey008** [comment]
Here is the fiddle:
[https://jsfiddle.net/vwaruz0c/](https://jsfiddle.net/vwaruz0c/)

I want column D to be salary + bonus, so I put the last column as 
` data: '=$B1+$C1'`

However this doesn't work, Handsontable doesn't calculate the sum for me.
I read through the Docs, in all examples the data are array of array, so I don't know how to do when data is an object.

Thanks.

**Comment by AMBudnik** [comment]
Currently, this https://jsfiddle.net/o6bjukq4/ is the only way to handle this operation.
