### ISSUE TITLE
Click-selecting the same cell multiple times adds multiple 'area' classes.

### ISSUE THREAD

**Issue by RichTeaTime** [handsontable/handsontable-pro#224]
### Description
Click-selecting the same cell multiple times adds up to seven 'area' class attributes. It should just maintain the existing selection if the area is the same as one that already exists (i.e. only highlight intersections of different areas).

### Steps to reproduce
1. Set grid to readOnly:true
2. Click a cell
3. Hold control and click the same cell again, and again, and again.
EXPECTED: Cell will remain selected (or, feature-request: toggle off!)
ACTUAL: Cell gets bluer and bluer, the more times you click, e.g.
![image](https://user-images.githubusercontent.com/16083760/53339646-d81ae280-38fe-11e9-8a16-886e6a976de4.png)

### Demo
https://jsfiddle.net/6otpng41/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 72.0.3626.109 
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
That's how `selectionMode: "multiple"` works. Sometimes called non-contiguous selection.

You're probably interested in other selection modes: https://handsontable.com/docs/Options.html#selectionMode

The feature request you've mentioned is covered by https://github.com/handsontable/handsontable/issues/5737 ?
