### ISSUE TITLE
Filters work incorrectly with `minRows` and `minSpareRows`

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable-pro#24]
### Description
When the `minRows` and `minSpareRows` are set to a certain number, Filtering and modifying data causes adding unwanted rows.

### Steps to reproduce

1. Go to http://jsfiddle.net/w7wy75k4/
2. Use the Filters on the first column, and filter out everything except "Lorem" 
3. Select the "Lorem" cell and press <kbd>Enter</kbd> twice

**Result:** The table gets filled with empty rows to match the number provided in `minRows` or `minSpareRows`. 
When you reset your filters, theres a "gap" of empty rows in your dataset.

### Demo
http://jsfiddle.net/w7wy75k4/

**Comment by AMBudnik** [comment]
Hi @jansiegel 

here's a similar case https://github.com/handsontable/handsontable/issues/3937

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

I have Handsontable with settings  minSpareRows : 1  and pro version filters. 

Also I  have header Checkbox and checkbox in rows as well. 
Steps to reproduce issue :-

1) Apply filter on records and then  select header checkbox.
2) Additional row gets added in handson table
3) Click on checkbox at row level, also row gets added .
4) Try  to clear filters, blank row is displayed in between handson table.

Hers is the fiddle link :- 

http://jsfiddle.net/1eg8dmsg/3/

**Comment by AMBudnik** [comment]
Hi @Sheetal1289 

The issue you described sounds exactly as this one https://github.com/handsontable/handsontable/issues/4801. Am I right? I have attached a video there as well.

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

Yes. Exactly same but in my case single row get added.

**Comment by AMBudnik** [comment]
Yes, cause it extra adds the exact amount in the `minSpareRows`

**Comment by Sheetal1289** [comment]
Hi @AMBudnik 

what will be the solution then ?

**Comment by alexon1234** [comment]
What I do:
1.  Instance handsontable with `minRows: 21`.
2.  In the afterFilter, set minRows a 1

Then the bug does not apply because to filter at least you need to have 1 result

**Comment by AMBudnik** [comment]
This issue should be solved in today's release. I will send an update as soon as we release an official version.
