### ISSUE TITLE
`autoRowSize` calculates row heights improperly, if dataset has been filtered out

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable-pro#26]
### Description
If an rows has different heights (because of multiline text), `autoRowSize` is enabled,  and dataset has been filtered, then, the row heights are desynchronized during vertical scrolling.

### Steps to reproduce
1. Filter out column 'A' with condition: 'Begins with' => 1
2. Scroll to the bottom edge

### Demo
https://jsfiddle.net/Ly03dnkb/

### Your environment
* Handsontable version: 1.0.0+
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Further investigated at https://github.com/handsontable/handsontable/issues/3618
