### ISSUE TITLE
Slow Performance when using formulas with large dataset

### ISSUE THREAD

**Issue by sava-vidakovic** [handsontable/handsontable-pro#3]
I noticed this issue with large data.
JSfiddle: https://jsfiddle.net/sava/cgpayh52/
On this demo formulas are disabled, try to enable and you will see the results.

Any suggestions to fix this?

**Comment by AMBudnik** [comment]
Hi @sava-vidakovic 

the Formula Support plugin is in alpha stage and it hasn't been optimized for larger datasets yet.

We are planning to update the plugin in Q4 2017 or in Q1 of 2018.

**Comment by abdulwahabplus** [comment]
I am facing similar problems with formula, Is the optimization has been done ?

**Comment by AMBudnik** [comment]
Hi @abdulwahabplus 

The process will take a little longer as it is regulated by one of our contracts.

Please check our[ ZenHub board](https://app.zenhub.com/workspace/o/handsontable/handsontable/boards?repos=1790564,85198294) for all the changes and fixes that we do.

**Comment by abdulwahabplus** [comment]
Thanks for your quick response.
I could see this defect as closed in Zenhub, when can I expect this to be released (approximately).

**Comment by AMBudnik** [comment]
Here is a [set of issues for formulas](https://app.zenhub.com/workspace/o/handsontable/handsontable/boards?repos=1790564,85198294&search=formula). We have a scheme already made but there are still some legal requirements that stop us. I am sorry but there is no deadline for this task yet.

**Comment by AMBudnik** [comment]
Hi @abdulwahabplus 

Can you send me your requirements at support[at]handsontable,com?
