### ISSUE TITLE
Long columns do not wrap when using Nested Headers

### ISSUE THREAD

**Issue by jmenglis** [handsontable/handsontable-pro#42]
Currently having an issue with longer columns being unable to wrap when using Nested Headers.

I have created a [jsfiddle](https://jsfiddle.net/joshenglish/3ec1tq3z/) to demonstrate the issue.

The problem is that the longer columns do not take on the size that is defined in column width and will not resize to wrap when dragging to resize.  

Version: 1.15.1
OS: Windows 7

**Comment by AMBudnik** [comment]
Hi @jmenglis 

Can you let me know that is an expected result (can be a drawing) as I am not sure if I understand it correctly?

**Comment by jmenglis** [comment]
[Video Demo of issue](https://www.useloom.com/share/fdac648d7e4d46abbcf9ee84243372d3)

Also if you notice the `colWidth` of that column is set to a really low value but it doesn't take that value.

**Comment by AMBudnik** [comment]
Oh, yes. I can see what you mean now. The column width is programmed to do not cut the header name. We would need to change or document it. You can use a hack with CSS to change the width https://jsfiddle.net/jdpw0bpu/2/

**Comment by SmoooZ** [comment]
facing this issue too with v2.0

**Comment by AMBudnik** [comment]
Hi @SmoooZ have you used the proposed code from https://jsfiddle.net/jdpw0bpu/2/?

**Comment by SmoooZ** [comment]
Hi @AMBudnik I cannot use this trick because I let the column header title wrap on multiple lines

**Comment by AMBudnik** [comment]
Yes, I also think that we should make it more flexible.

**Comment by xoneill** [comment]
Why is it closed? What was the solution?

**Comment by jmenglis** [comment]
My fault accidently closed this.

**Comment by xoneill** [comment]
I found a workaround:
- create a CSS class with width property. E.g. `hot-header-fix: {width: 50px}`
- apply it to your header element
- then remove it in the hook **afterGetColHeader**
And you will be able to resize the column headers again

**Comment by AMBudnik** [comment]
Thank you for sharing and doing the investigation @xoneill

**Comment by JoshSchreuder** [comment]
Would love a permanent fix for this issue.
I think it did work differently at some point (we're upgrading from 1.8.0 to 6.1.1) as it did used to wrap on nested headers.

**Comment by JoshSchreuder** [comment]
@AMBudnik can you give us the ability to turn off the GhostTable widthsMapper stuff in nested headers?

If I comment out the code to build the `widthsCache`:

```js
for (var i = 0; i < maxColumns; i++) {
  this.widthsCache.push(columns[i].offsetWidth);
}
```

The table pretty much behaves exactly as I want it to.

**Comment by JoshSchreuder** [comment]
Actually I found another hacky sort of workaround by calling into the plugin and resetting the widthCache on render:

```
afterRender: function () {
    this.getPlugin('nestedHeaders').ghostTable.widthsCache = [];
},
```

I'd rather have a proper supported option so that this doesn't break future updates for me if possible :)

**Comment by AMBudnik** [comment]
mentioned at https://github.com/handsontable/handsontable/issues/4021
