### ISSUE TITLE
afterePaste of Documentation  It is not working

### ISSUE THREAD

**Issue by hand-dot** [handsontable/handsontable-pro#5]
Hi! I found spelling mistakes in Handsontable Pro's Documentation.
It is the URL - https://docs.handsontable.com/pro/1.14.2/Hooks.html#event:afterePaste

afterPaste is working!

**Comment by AMBudnik** [comment]
Thanks for spotting that @hand-dot

**Comment by AMBudnik** [comment]
Hi @hand-dot 

I am just checking in to inform that the fix has been merged to the develop branch. It will be a part of the new release.

**Comment by AMBudnik** [comment]
The issue has been fixed https://docs.handsontable.com/pro/4.0.0/Hooks.html#event:afterPaste
Thank you @hand-dot
