### ISSUE TITLE
A new row is not visible after a call to render (when option nestedRows is true)

### ISSUE THREAD

**Issue by nlips** [handsontable/handsontable-pro#63]
### Description
My table is configured with option `nestedRows = true`.
I have a form to add a row .
When form is submited I add a row to the handsontable settings data array and I call `render()`.
The new row is not visible !

### Steps to reproduce
See the jsfiddle demo

### Demo
https://jsfiddle.net/nlips/o32srtm7/

### Your environment
* Handsontable version: 1.18.1
* Browser Name and version: Chrome Version 65.0.3325.181
* Operating System: WIndows 10

**Comment by AMBudnik** [comment]
Hi @nlips 

You've missed the `hot.loadData(data)` in this example. 

However, if we do it we still get an error https://jsfiddle.net/handsoncode/5n5rL5h1/ even when the object scheme is correct.
For a split of a second a new rowHeader is added but calculations fail and we get a console error.

Please give me a moment. I will test it more.

**Comment by AMBudnik** [comment]
It looks like the data if used for `nestedRows `is immune to programmatic changes, but I would need to check this little bit closer as it seems really odd.

Here https://jsfiddle.net/handsoncode/19madffo/ I is a workaround for your scenario.

**Comment by nlips** [comment]
A call to `loadData` should not be necessary since Handsontable binds to data source by reference (as explained here : [https://docs.handsontable.com/pro/1.18.1/tutorial-data-binding.html](https://docs.handsontable.com/pro/1.18.1/tutorial-data-binding.html))

**Comment by wojciechczerniak** [comment]
Data binding through reference works only for simple use cases. With plugins that have complex meta data it's necessary to update them as well. You would have to call hooks like `afterCreateRow` so the nested rows plugin will know that it has to update. Or use the `observeChanges` plugin, but we want to deprecate it soon.

The better approach here is to use Handsotnable API `setDataAtRowProp`: https://jsfiddle.net/3w24b7qm/ Hooks are called internally and everything is updated. And you don't have to call the `render()` function.
