### ISSUE TITLE
`disablePlugin` of the Gantt Chart plugin doesn't work properly

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable-pro#68]
### Description
The `disablePlugin` method from the Gantt Chart plugin doesn't work properly.

It's probably caused by improper declaration of `this.initialSettings` + issues with re-enabling the plugin using `updateSettings`.

### Steps to reproduce

1. http://jsfiddle.net/js_ziggle/g8p8rek2/
**Result:** The table is misaligned and not reverted from the state before enabling the plugin.

### Demo
http://jsfiddle.net/js_ziggle/g8p8rek2/

**Comment by AMBudnik** [comment]
Changed in v `7.0.0` http://jsfiddle.net/8uprw6f3/
