### ISSUE TITLE
Handsontable is not defined

### ISSUE THREAD

**Issue by bchoddny** [handsontable/handsontable-pro#7]
Hi,
I'm trying to migrate from handsontable-pro 1.3.0 to the latest 1.14.2. I understood there are breaking changes, but experimenting the upgrade. The requirejs config that use to work fine with 1.3.0 doesn't work with the latest version. I keep getting "ReferenceError: Handsontable is not defined". Please advise, Thanks.

`require.config({
paths: {
'jquery': '../components/jquery/jquery',
'bootstrap': '../components/bootstrap-javascript/bootstrap',
'handsontable': '../components/handsontable-pro/dist/handsontable.full',
// hot-pro dependencies
'pikaday': '../components/pikaday/pikaday',
'zeroclipboard': '../components/zeroclipboard/dist/ZeroClipboard',
'moment': '../components/moment/moment',
'hot-formula-parser': '../components/hot-formula-parser/dist/formula-parser',
'numbro': '../components/numbro/dist/numbro'
},

shim: {
    'handsontable': {
        exports: 'Handsontable',
        deps: ['pikaday', 'zeroclipboard', 'moment', 'numbro', 'hot-formula-parser']
    },
    'cm-handsontable-pro': ['handsontable', 'select2', 'dompurify']
}
});

I tried the [suggestion](https://github.com/handsontable/ngHandsontable/issues/169) in this issue, but doesn't seem to work.

**Comment by bchoddny** [comment]
Does handsontable-pro 1.14.2 supports AMD?

**Comment by bchoddny** [comment]
I have also created [jsfiddle](http://jsfiddle.net/g7b5syck/38/) to illustrate the problem. You'll notice the output of the last line is undefined :

console.log('Require.js Handsontable Version: ' + Handsontable);

**Comment by AMBudnik** [comment]
Thank you for sharing the demo. I will test it and get back to you tomorrow.

**Comment by AMBudnik** [comment]
Sorry for keeping you waiting. Did you already found a solution?

**Comment by bchoddny** [comment]
Not yet. Please advise. Thanks.

**Comment by bchoddny** [comment]
I'm using requirejs for loading modules, as you can see in my fiddle. I would love to see a working example of latest version of handsontable using AMD

**Comment by AMBudnik** [comment]
I am really sorry but as we have checked Handsontable doesn't work with requirejs

**Comment by bhosaleatul-syn** [comment]
@AMBudnik as you mention in your last post, "However, it looks like there's some kind of workaround. Please check the demo http://jsfiddle.net/g7b5syck/38/". But the jsfiddle URL is same as URL posted in @bchoddny post and it is still showing undefined.
Also, for me version 1.9.1 is working properly with requirejs

Is any one found any solution???

**Comment by AMBudnik** [comment]
I have checked the demo and, unfortunately, the subject exceeds my ability to help. We need a developer help here. Please notice that this can take little more time.

**Comment by strandedcity** [comment]
I hit this issue but got it working by using the normal version of the library and including the dependencies separately, not the `full` version that packages the dependencies. More details here: https://stackoverflow.com/questions/28719633/using-handsontable-with-requirejs

This is as of 0.35.0, 12/9/17

Hope that helps anyone who finds this in the future!

**Comment by AMBudnik** [comment]
Thank you for your support @strandedcity
