### ISSUE TITLE
beforeColumnResize incorrect arguments

### ISSUE THREAD

**Issue by nlips** [handsontable/handsontable-pro#71]
### Description
beforeColumnResize  hook is called with incorrect arguments.

### Steps to reproduce
1. settings : manualColumnResize: true and beforeColumnResize callback with 3 arguments : colIndex, newSize, isDblClick
2. run and resize a column manualy
3. beforeColumnResize callback is called but with first and second argument having the same value (the new size)

### Demo
https://jsfiddle.net/nlips/Lg8LLgjz/

### Your environment
* Handsontable version: 1.18.1
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @nlips 

I believe that this issue is already mentioned at https://github.com/handsontable/handsontable/issues/3328

Please let me know if I'm right.

**Comment by AMBudnik** [comment]
I am closing this issue. Please track the mentioned topic.
