### ISSUE TITLE
`hiddenColumns` plugin unsets cell's `renderer`

### ISSUE THREAD

**Issue by bob-frost** [handsontable/handsontable-pro#76]
### Description
Name of original renderer can't be obtained with `getCellMeta(row, col).baseRenderer` or `getCellMeta(row, col).renderer` if `hiddenColumns` plugin is enabled and column is not hidden initially.
As far as I understood `hiddenColumns` should copy original renderer to `baseRenderer` property of meta when column is hidden and restore it back to `renderer` when column is displayed. Instead `renderer` becomes `undefined` and `baseRenderer` is `null`
Seems that issue is on this line: https://github.com/handsontable/handsontable-pro/blob/938ac9d34382320b313e6cd8dd103474eaa7d878/src/plugins/hiddenColumns/hiddenColumns.js#L255 Condition should be `else if (!cellProperties.baseRenderer)` because initially `baseRenderer` is not `null` but `undefined`.

### Steps to reproduce
See console in the jsfiddle demo

### Demo
https://jsfiddle.net/bob_usenakunov/L46xqezg/7/

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Chrome 66.0.3359.181
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Thank you for sharing the investigation results. I will ask our developer to check that and be back soon.

**Comment by AMBudnik** [comment]
Hi @bob-frost 

the code generates a `No registered renderer found under "null" ` report, I think that you can use the `cellProperties.baseRenderer != null` instead but I'm not fully sure if I understand the case. If that won't help can you tell me a little bit more about the problem?

**Comment by bob-frost** [comment]
@AMBudnik I have few custom renderers and need to be able to identify them.
Without `hiddenColumns` plugin there was smth like this:

```
const isReactCell = (hotInstance, row, col) => {
  const renderer = hotInstance.getCellMeta(row, col).renderer;
  return renderer && renderer.startsWith('react');
};
```

After adding `hiddenColumns` to table there is no way to get renderer name from cell meta. I found another way to do it:
```
const isReactCell = (hotInstance, row, col) => {
  const renderer = hotInstance.getSettings().columns[col].renderer;
  return renderer && renderer.startsWith('react');
};
```

But it seems that it would be more proper way to keep renderer accessible from cell meta

**Comment by AMBudnik** [comment]
Thank you for sharing this tip. I will ask our developers to take a look at it.

**Comment by AMBudnik** [comment]
We're moving the issues to the **handsontable** repository as we no longer work on **handsontable-pro**.
