### ISSUE TITLE
Color Text combination autocomplete box

### ISSUE THREAD

**Issue by gauthamshettykaup** [handsontable/handsontable-pro#8]
I was able to create drop down of colour & text pairs. Then I was able to display colour & text combination in autocomplete box fields in view mode.
But I’ve problem in edit mode of autocomplete box. Here we should have text say text value should be displayed in grid rather  than html text.

I’ve spend some time on this. I couldn’t figure out direct approach. Here we are getting colours and text value from API. Then we are creating html datasource for 
Autocomplete box. I’m able to create drop down source with colour and text combination. After selecting value from drop down it will be getting displaced in Autocomplete
Box. In view mode it works. As shown in figure it gets displayed properly. 

When control goes to edit mode. Since this text is html. It will get displayed like html. We don’t want html rather we want only text value. I’ve spent little time on this. I couldn’t find
direct approach over here. So, I’m sharing this problem. Hoping somebody in group might to be knowing solution to this problem.

I’ve describe problem in below image. Please help me on this regards.

Although, this is not an issue its kind of new feature I believe. Still any body over here has workaround. Hoping to share with me.

**Comment by AMBudnik** [comment]
Hi @gauthamshettykaup 

I am afraid that it will be only available via handsontable cell type. You can find it at https://docs.handsontable.com/pro/1.14.3/demo-handsontable.html

Here is a sample demo http://jsfiddle.net/5h0gsw1s/

**Comment by gauthamshettykaup** [comment]
**@AMBudnik -** 
1) Even during view mode I need colour+value should be displayed
2) It should have filter behaviour on *Value*.

I've gone through this example earlier because of above two problem I couldn't proceed. looking for your help in this line.

Regards,
Gautham

**Comment by AMBudnik** [comment]
Sorry but I am not sure what you mean by writing 

> It should have filter behaviour on Value.

Could you please describe the behavior?

**Comment by gauthamshettykaup** [comment]
Sorry @AMBudnik AMBudnik I was late responding you. To make things clear I have created two fiddler:
In view and Edit mode I want achieve like this:

**1) https://jsfiddle.net/gauthamshettykaup/w9zhrboh/8/**
Which I've achieve on **handsontable-pro** 

2)Second I've to achieve like this during autocomplete filtering mode.
**http://jsfiddle.net/gauthamshettykaup/eyj4j4q6/16/**

![screen shot 2017-10-26 at 5 01 30 pm](https://user-images.githubusercontent.com/12834108/32050698-63e212bc-ba6f-11e7-8858-57b0a97d5b3f.png)

In this example they are using **highlighter: colorHighlighter,** but couldn't incorporate this in first example. Please help on this regard.

Regards,
Gautham

**Comment by gauthamshettykaup** [comment]
I was able to fix this issue.

**Comment by AMBudnik** [comment]
Hi @gauthamshettykaup 

thank you for an update. I am happy that you've found a solution.
