### ISSUE TITLE
how can I use export file plugin

### ISSUE THREAD

**Issue by noninyo** [handsontable/handsontable-pro#84]
I would like to export my table as csv file but in vue I don't have the hot object

**Comment by AMBudnik** [comment]
Hi @noninyo 
Have you defined the table via `ref`?
`<HotTable ref="handsontable" :root="root" :settings="hotSettings"></HotTable>`

**Comment by AMBudnik** [comment]
Can you push a demo on the Stackblitz? Here's a demo that you can use as a base https://stackblitz.com/edit/angular-ivnm3m?file=src/app/hello.component.ts

**Comment by noninyo** [comment]
I am working with VeuJS
here is jsfiddle:
https://jsfiddle.net/noninyo/0v7r3mw2/

Thanks

**Comment by AMBudnik** [comment]
Hi @noninyo 

to use `getPlugin` you need to add `table` - var exportPlugin = this.$refs.handsontable.table.getPlugin('exportFile');
and you're using the CE version here so remember to check if you added PRO scripts.

**Comment by noninyo** [comment]
Thanks!
it works :)
I am using Pro but didn't know how to set it in example with out write my licence
