### ISSUE TITLE
Table loses its linearity

### ISSUE THREAD

**Issue by BadiuAlexandru** [handsontable/handsontable-pro#9]
I reproduce this issue on fiddle  : http://jsfiddle.net/AlexandruAlin/1z67cvwL/2/

If you scroll to latest week , you will see that it loses its linearity.

**Comment by AMBudnik** [comment]
Hi @BadiuAlexandru 

It is a known bug, however, there is also a workaround. You can add the viewportColumnRenderingOffset option. It will correspond to the number of columns you want to show.

Here's an updated example http://jsfiddle.net/of87xmkv/

ps. the number of columns in all nested rows levels has to be the same. In the highest lvl you have 57 columns and in a level below it's 56.
