### ISSUE TITLE
formula variables change unable to trigger re render Hottable

### ISSUE THREAD

**Issue by xma58** [handsontable/handsontable-pro#90]
I am pretty new to Handsontable, any help will be appreciated. In this app, I am using redux to change the variables. I would want to re render (and recalculated) the table component every time after I make changes to "variables: this.props.assumptions". Is there anything I did wrong? suggestions? Thanks. :)

```
<HotTable
          root="hot"
          ref="hot"
          preventOverflow="horizontal"
          settings={{
            colHeaders: true,
            rowHeaders: true,
            data: this.props.cells,
            minRows: 15,
            minCols: 26,
            observeChanges: true,
            outsideClickDeselects: false,
            formulas: {
              variables: this.props.assumptions
            },
            afterOnCellMouseDown: this.handleAfterOnCellMouseDown,
            afterChange: this.handleAfterChange,
            afterSelection: this.handleAfterSelection
          }}
        />

```

**Comment by AMBudnik** [comment]
Hi @xma58 

the [render()](https://docs.handsontable.com/pro/4.0.0/Core.html#render) method is used to rerender the table.

**Comment by xma58** [comment]
Yes, I have the render function, the hottable is put in the render(), but still I seemed not able to get the table recalculated with the new variables.

**Comment by AMBudnik** [comment]
Can you share your implementation via JSFiddle or Stackblitz? I'll test it

**Comment by AMBudnik** [comment]
I'm closing the issue as there is no reply for more than a month.
