### ISSUE TITLE
handsontable-pro copy a form cant reserve its format

### ISSUE THREAD

**Issue by rianran1993** [handsontable/handsontable-pro#92]
### Description
handsontable-pro  copy a  2*2form  from excel cant reserve the format，but it work in handsontable-ce

![pro-copypast](https://user-images.githubusercontent.com/22359049/42429531-f79e1a3a-836b-11e8-876d-7f5828dab0d4.gif)

### Steps to reproduce

1.
2.
3.

### Demo
https://jsfiddle.net/aqufmj72/3/

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hi @rianran1993 

Handsontable copies only pure data it doesn't copy formatting and styling.

**Comment by rianran1993** [comment]
@AMBudnik 
 but it copy formatting and styling in ce edition 
![ce-copypast](https://user-images.githubusercontent.com/22359049/42433325-694b4274-8381-11e8-9348-d0f523816657.gif)

**Comment by AMBudnik** [comment]
The result is different as the demo for PRO has to have some formatting already applied and `4,00` is a value - not a formatted `4`.

Please check the example below for [our scrolling demo](https://docs.handsontable.com/pro/4.0.0/demo-scrolling.html), which doesn't have any formatting enabled.

### CE
![ce](https://user-images.githubusercontent.com/10757813/42433959-9b7a08f0-8351-11e8-949d-c21180dd2b8f.gif)
### PRO
![pro](https://user-images.githubusercontent.com/10757813/42433960-9ba17f84-8351-11e8-9fda-23e6e1ef55be.gif)

**Comment by rianran1993** [comment]
ok, thanks! it suddenly be ok today.....
