### ISSUE TITLE
Cannot find module when i create a test (jest)

### ISSUE THREAD

**Issue by jericbas** [handsontable/handsontable-pro#97]
### Description
I'm creating a react component

### Demo
` ● Test suite failed to run

    Cannot find module 'handsontable/plugins/_base' from 'bindRowsWithHeaders.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/handsontable-pro/commonjs/plugins/bindRowsWithHeaders/bindRowsWithHeaders.js:9:13)`

### Your environment
* Handsontable version: 5.0.0

**Comment by AMBudnik** [comment]
Hi @jericbas 

we've tried to replicate and did not get the same issue. Have you used `npm i` before step 4?

**Comment by AMBudnik** [comment]
I believe that this is no longer an issue as there's no reply for more than 3 weeks.
